version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: start-to-end-postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: start-to-end-app:local
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgre
      SPRING_DATASOURCE_PASSWORD: postgre
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  db_data:
