FROM postgres:16.10-alpine

ENV POSTGRES_DB=mydb
ENV POSTGRES_USER=postgre
ENV POSTGRES_PASSWORD=postgre

EXPOSE 5432

# Optional: mount volume for persistent data
VOLUME ["/var/lib/postgresql/data"]
