spring:
  application:
    name: StartToEndDeploymentFlow
  main:
    banner-mode: off
    lazy-initialization: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgre}
    password: ${SPRING_DATASOURCE_PASSWORD:postgre}
    hikari:
      minimum-idle: 0
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    org.hibernate.SQL: off
